import { expect, test } from "vitest";
import { jsxToString } from "jsx-async-runtime";
import { Head } from "./Head";
import { HeadSchema } from "../../eleventy";

const defaultProps = {
  title: "Breathe Easy Sheffield",
  description:
    "An eclectic series of Covid safer social & cultural events, designed with enhanced safety measures in place to reduce transmission risk. Launching autumn 2024.",
  socialImage: "/static/img/ogimage-default.png",
  socialImageAlt: "Breath Easy's logo",
};

test("Head produces title metadata", async () => {
  const data = {
    baseUrl: "https://example.com",
    title: "snazzy website",
    page: { url: "/" },
  };

  const result = Head(HeadSchema.parse(data));
  document.head.innerHTML = await jsxToString(result);

  expect(document.querySelector("title").textContent).to.equal(data.title);
  expect(document.querySelector("meta[name='title']").content).to.equal(
    data.title,
  );
  expect(document.querySelector("meta[property='og:title']").content).to.equal(
    data.title,
  );
});

test("social image is present and has alt text", async () => {
  const data = {
    baseUrl: "https://example.com",
    title: "snazzy website",
    page: { url: "/" },
  };

  const result = Head(HeadSchema.parse(data));
  document.head.innerHTML = await jsxToString(result);

  expect(document.querySelector("meta[property='og:image']").content).to.equal(
    data.baseUrl + defaultProps.socialImage,
  );
  expect(
    document.querySelector("meta[property='og:image:alt']").content,
  ).to.equal(defaultProps.socialImageAlt);
});

test("link metadata exists", async () => {
  const data = {
    title: "snazzy website",
    page: { url: "/" },
  };

  const result = Head(HeadSchema.parse(data));
  document.head.innerHTML = await jsxToString(result);

  expect(document.querySelector("meta[property='og:url']")?.content).to.equal(
    "/",
  );
  expect(document.querySelector("link[rel='canonical']").href).to.equal(
    "http://localhost:3000/", // generated by host enviroment
  );
});

test("description metadata exists", async () => {
  const data = {
    baseUrl: "https://example.com",
    title: "snazzy website",
    page: { url: "/" },
  };

  const result = Head(HeadSchema.parse(data));
  document.head.innerHTML = await jsxToString(result);
  expect(document.querySelector("meta[name='description']").content).to.equal(
    defaultProps.description,
  );
  expect(
    document.querySelector("meta[property='og:description']").content,
  ).to.equal(defaultProps.description);
});
